# Generated by Django 4.2 on 2023-04-29 01:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('league_name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('match_name', models.CharField(default='', max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('team_1', models.CharField(max_length=100)),
                ('team_2', models.CharField(max_length=100)),
                ('score', models.CharField(default='TBD', max_length=20)),
                ('is_live', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('is_user_uploaded', models.BooleanField(default=True)),
                ('match_link', models.URLField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.league')),
            ],
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('highlight_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(default='')),
                ('highlight_action', models.CharField(max_length=10, null=True)),
                ('match_time', models.CharField(default='00:00', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
    ]
