# Generated by Django 4.2 on 2023-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='is_user_uploaded',
            field=models.BooleanField(null=True),
        ),
    ]
