# Generated by Django 4.1.7 on 2023-05-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_target_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='target_link',
            field=models.URLField(default='http://127.0.0.1:8000/', null=True),
        ),
    ]
